#!/bin/sh
# get the path to this script
DIR="$( cd "$( dirname "$0" )" && pwd )"
#set cpan local::lib to the same dir
cpanm --local-lib=$DIR/perl5 local::lib >> /dev/null && eval $(perl -I $DIR/perl5/lib/perl5/ -Mlocal::lib) >> /dev/null
$DIR/slic3r.pl $@
